api: {}

providers:
  file:
    filename: "/etc/traefik/dynamic.yaml"
  docker:
    exposedByDefault: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
  https:
    address: ":443"
  traefik:
    address: ":8080"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "test@example.com"
      storage: "acme.json"
      tlsChallenge: {}
